name: Deploy to EC2

on:
  push:
    branches:
      - piyara2000-patch-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run npm install
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ec2-user/TutorMeister/Controller
          npm install

    - name: Run npm test
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ec2-user/TutorMeister/Controller
          npm test || true 

    - name: Deploy changes
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          cd /home/ec2-user/TutorMeister/Controller
          /usr/bin/git pull origin main
          npm install

          kill -9 $(/usr/sbin/lsof -t -i:5000) || true

          npm start > /dev/null 2>&1 &
          echo $! > deploy_pid

          sleep 10
          exit 0
