name: Deploy to EC2

on:
  push:
    branches:
      - piyara2000-patch-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: 'v1'
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-48-58-172.eu-north-1.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ec2-user/TutorMeister/Controller
          git pull origin main
          npm install
          npm start &
          exit 0
