name: Deploy to EC2

on:
  push:
    branches:
      - piyara2000-patch-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Navigate to Controller directory
      run: cd /home/ec2-user/TutorMeister/Controller

    - name: Install dependencies
      run: npm install

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Navigate to Controller directory
      run: cd /home/ec2-user/TutorMeister/Controller

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Navigate to Controller directory
      run: cd /home/ec2-user/TutorMeister/Controller

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        script: |
          git pull origin main
          npm install
          npm test

          kill -9 $(lsof -t -i:5000) || true

          npm start > /dev/null 2>&1 &

          echo $! > deploy_pid

          sleep 10
          exit 0
